### ISSUE TITLE
TypeError: Value passed to parameter 'paddings' has DataType float32 not in list of allowed values: int32, int64

### ISSUE THREAD

**Issue by chenguanqi** [zhimingluo/NLDF#4]
Hi, when I run the code in tf=1.3.0, I met the following error:
File "NLDF.py", line 126, in Contrast_Layer
return tf.subtract(input_, tf.nn.avg_pool(tf.pad(input_, [[0, 0], [h_s, h_s], [h_s, h_s], [0, 0]], 'SYMMETRIC'),
TypeError: Value passed to parameter 'paddings' has DataType float32 not in list of allowed values: int32, int64.
How can I fix it?

**Comment by chenguanqi** [comment]
I modified the function Contrast_Layer(self, input_, k_s=3) as follow:
def Contrast_Layer(self, input_, k_s=3):
        # h_s = k_s / 2 
        # return tf.subtract(input_, tf.nn.avg_pool(tf.pad(input_, [[0, 0], [h_s, h_s], [h_s, h_s], [0, 0]], 'SYMMETRIC') ,ksize=[1, k_s, k_s, 1], strides=[1, 1, 1, 1], padding='VALID'))
        h_s = k_s // 2
        if k_s % 2 == 0:
            return tf.subtract(input_, tf.nn.avg_pool(tf.pad(input_, [[0, 0], [h_s, h_s], [h_s, h_s], [0, 0]], 'SYMMETRIC'), ksize=[1, k_s, k_s, 1], strides=[1, 1, 1, 1], padding='VALID'))
        else:
            return tf.subtract(input_, tf.nn.avg_pool(tf.pad(input_, [[0, 0], [h_s, h_s+1], [h_s, h_s+1], [0, 0]], 'SYMMETRIC'),ksize=[1, k_s, k_s, 1], strides=[1, 1, 1, 1], padding='VALID'))

Is it right?

**Comment by zhanpx** [comment]
我也遇到这个问题，我直接改成  h_s = int(k_s / 2) 了

**Comment by chenguanqi** [comment]
> 我也遇到这个问题，我直接改成 h_s = int(k_s / 2) 了

好的，谢谢
